<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_PU_Schuetz_Output" Id="{c1e26745-fd91-47ab-bf4b-0bb432bbd5ad}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PU_Schuetz_Output
VAR_INPUT
	Stellung			: BOOL;
END_VAR
VAR_OUTPUT
	OUT_Stellung	: BOOL;
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[OUT_Stellung := Stellung;]]></ST>
    </Implementation>
    <LineIds Name="FB_PU_Schuetz_Output">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>