<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_SVs_Output" Id="{0c8b6cec-f274-4b5d-b0c7-cf08d41ebbf8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SVs_Output
VAR_INPUT
	Stellung : BOOL;
END_VAR
VAR_OUTPUT
	OUT_Stellung : BOOL;
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[OUT_Stellung := Stellung;]]></ST>
    </Implementation>
    <LineIds Name="FB_SVs_Output">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>