<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="com_task" Id="{2a6820b0-4f66-4d85-a976-c6f73a5f0ae5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM com_task
VAR
	try : BOOL := FALSE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* Zähler *)
Zaehler();

(* Wetterstation *)
Wetterstation();


try :=  TRUE;]]></ST>
    </Implementation>
    <LineIds Name="com_task">
      <LineId Id="4" Count="7" />
    </LineIds>
  </POU>
</TcPlcObject>