<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="IEEE32_TO_REAL" Id="{0ad90c61-97e8-4bd6-bbc7-678ff1cf5421}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION IEEE32_TO_REAL : REAL
VAR_INPUT
	IN:DWORD;
END_VAR
VAR
	PTREAL:POINTER TO REAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[PTREAL:=ADR(IN);
IEEE32_TO_REAL:=PTREAL^;]]></ST>
    </Implementation>
    <LineIds Name="IEEE32_TO_REAL">
      <LineId Id="7" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>