<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_HeatExchanger1" Id="{bca56c6b-1b09-4f57-a186-5b7562770c5b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HeatExchanger1 EXTENDS FB_SystemContinous
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*
- implementierung ähnlich zu wärmetauscher system bei hvfa speichern
- bestehend aus 2 Magna 3 pumpen (PU315, PU215)
- disrcete valve SV315
- mixing valve RV215
- heat counter WMZ215

Logik:
- RampUp: SV und RV öffnen
- Operational: PUs anschalten
- Working: RV regelt auf Vorlauftemepratur an PWT1
- RampDown: Umgekehrte Reihenfolge

- errorCheck: Prüfe auf pumpenerror, falls SV315 Stellugnsrückmeldung hat (in aktuellem bei Verknüpfungen prüfen), dann prüfen ob pumpe gegen geschlossenes Ventil pumpt
*)]]></ST>
    </Implementation>
    <LineIds Name="FB_HeatExchanger1">
      <LineId Id="9" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="22" Count="2" />
      <LineId Id="26" Count="0" />
      <LineId Id="25" Count="0" />
      <LineId Id="27" Count="3" />
      <LineId Id="32" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="18" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>