<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_System_BelAu_Sensorik" Id="{83577a62-dd5e-46d6-9e66-a212e4d24a53}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_System_BelAu_Sensorik
VAR_INPUT
END_VAR
VAR_OUTPUT
	(* Dunkelheit Sensor 1*)
	Dunkelheit_OUT	: REAL;
END_VAR
VAR
	(* Hardware oder DALI *)
	Dunkelheit_IN		: REAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* ggfs Umrechung *)
Dunkelheit_OUT := Dunkelheit_IN * 3 ;]]></ST>
    </Implementation>
    <LineIds Name="FB_System_BelAu_Sensorik">
      <LineId Id="11" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>