<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_RV_Output" Id="{e967feef-cb0c-42fd-a763-38ed25b3797d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_RV_Output
VAR_INPUT
	Betrieb				:BOOL;
	Stellung			:USINT;
END_VAR
VAR_OUTPUT
	OUT_Stellung		: INT;
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[OUT_Stellung 		:= USINT_TO_INT(Stellung) * 327;]]></ST>
    </Implementation>
    <LineIds Name="FB_RV_Output">
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>