<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_BHKW_Input" Id="{e87c0bca-6793-4342-9c59-e14ffca6b131}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_BHKW_Input
VAR_INPUT
	IN_Sammelstoerung		: BOOL;
END_VAR
VAR_OUTPUT
	Sammelstoerung			: BOOL;
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Sammelstoerung := IN_Sammelstoerung;]]></ST>
    </Implementation>
    <LineIds Name="FB_BHKW_Input">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>