<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_BvL_CleaningSystem" Id="{33be35a8-bbc7-4c5f-8b7d-f73b38460099}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_BvL_CleaningSystem
VAR_INPUT
END_VAR
VAR_OUTPUT
	bError_Connection : BOOL;
	bHNHT_Demand : BOOL; 
END_VAR
VAR
	//I/O-Links
	Technical_Heat_RZ_SV AT %I* : BOOL;
	Technical_Heat_RZ_PWW AT %I* : BOOL;
	Technical_Heat_RZ_UWP AT %I* : BOOL;
	Technical_Heat_SZ_SV AT %I* : BOOL;
	Technical_Heat_SZ_PWW AT %I* : BOOL;
	Technical_Heat_SZ_UWP AT %I* : BOOL; 
	ConnectionStatus_OPC_BvL AT %I* : BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[bHNHT_Demand := (Technical_Heat_RZ_PWW OR Technical_Heat_RZ_SV OR Technical_Heat_RZ_UWP OR Technical_Heat_SZ_PWW OR Technical_Heat_SZ_SV OR Technical_Heat_SZ_UWP) AND ConnectionStatus_OPC_BvL;
bError_Connection := NOT ConnectionStatus_OPC_BvL;
]]></ST>
    </Implementation>
    <LineIds Name="FB_BvL_CleaningSystem">
      <LineId Id="212" Count="1" />
      <LineId Id="181" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>