<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_Ventilation" Id="{b3736a55-8dec-49ad-8b80-0e1e5782a762}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Ventilation EXTENDS FB_ActuatorContinous
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Ventilation">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>